export const DB = {
    "AWS::CertificateManager::Certificate": {
        "DomainName": {
            "type": "string",
            "nameItRight": {
                "autogenerated_regex_explanation": "",
                "service_plain_english_name": "",
                "list_rules_plain_english": ["User names can be a combination of up to 64 letters, digits, and these characters: plus (+), equal (=), comma (,), period (.), at sign (@), underscore (_), and hyphen (-). Names must be unique within an account. They are not distinguished by case. For example, you cannot create two users named TESTUSER and testuser."],
                "list_custom_patterns": ["^[a-zA-Z0-9+=,\\.@_-]{1,64}"],
                "list_documentation_urls": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html?icmpid=docs_iam_console" , "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html"],
                "list_other_sources_urls": [],
                "list_errors": [],
                "name_change_possible": true
            }
        },
        "SubjectAlternativeNames": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        }
    },
    "AWS::CloudFront::Distribution": {
        "DomainName": {
            "type": "string"
        }
    },
    "AWS::CloudWatch::Alarm": {
        "Namespace": {
            "type": "string"
        },
        "MetricName": {
            "type": "string"
        },
        "AlarmName": {
            "type": "string"
        }
    },
    "AWS::Route53::RecordSetGroup": {
        "HostedZoneName": {
            "type": "string"
        }
    },
    "AWS::S3::Bucket": {
        "BucketName": {
            "description": "A name for the bucket. If you don't specify a name, AWS CloudFormation generates a unique physical ID and uses that ID for the bucket name.",
            "maxLength": 63,
            "minLength": 3,
            "pattern": "^[a-z0-9][a-z0-9//.//-]*[a-z0-9]$",
            "type": "string"
        },
        "DomainName": {
            "description": "The IPv4 DNS name of the specified bucket.",
            "examples": [
                "mystack-mybucket-kdwwxmddtr2g.s3.amazonaws.com"
            ],
            "type": "string"
        },
        "DualStackDomainName": {
            "description": "The IPv6 DNS name of the specified bucket. For more information about dual-stack endpoints, see [Using Amazon S3 Dual-Stack Endpoints](https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html).",
            "examples": [
                "mystack-mybucket-kdwwxmddtr2g.s3.dualstack.us-east-2.amazonaws.com"
            ],
            "type": "string"
        },
        "RegionalDomainName": {
            "description": "Returns the regional domain name of the specified bucket.",
            "examples": [
                "mystack-mybucket-kdwwxmddtr2g.s3.us-east-2.amazonaws.com"
            ],
            "type": "string"
        }
    }
}